version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.8  # primary container for the build job
    steps:
      - checkout
      - run:
          command: |
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
      - run:
          command: |
            source venv/bin/activate
            python manage.py test
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy por ssh
          command: |
            ssh jmacboy@ssh.pythonanywhere.com "ls"
workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
